import type { SeoPluginOptions } from '../types.js';

export function renderRobots(_ctx: any, options: SeoPluginOptions): Response {
  const siteUrl = options.siteUrl.replace(/\/+$/, '');

  const content = `# Robots.txt (Generated by EmDash SEO Suite)
User-agent: *
Disallow: /_emdash/
Disallow: /api/
Allow: /

# Dynamic Sitemaps
Sitemap: ${siteUrl}/sitemap.xml
Sitemap: ${siteUrl}/sitemap_index.xml

# AI Agent Directives
User-agent: GPTBot
Allow: /
Allow: /llms.txt

User-agent: ClaudeBot
Allow: /
Allow: /llms.txt

User-agent: PerplexityBot
Allow: /
Allow: /llms.txt
`;

  return new Response(content, {
    status: 200,
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'public, max-age=86400',
    },
  });
}
